import { NextRequest, NextResponse } from "next/server";
import { ActionsService } from "../../../../lib/services/actions";

export async function GET(request: NextRequest) {
  try {
    // Get the next action from the service
    const nextAction = await ActionsService.getNextAction();
    
    if (!nextAction) {
      return NextResponse.json({
        success: true,
        data: null
      });
    }
    
    // Get the detailed action data with relationships
    const actionDetails = await ActionsService.getActionDetailResource(nextAction.id);
    
    // Parent summaries are read directly from database columns
    // (they're automatically generated and regenerated by the ParentSummaryService)
    const enhancedActionDetails = {
      ...actionDetails,
      parent_context_summary: actionDetails.parent_context_summary || 'This action has no parent context.',
      parent_vision_summary: actionDetails.parent_vision_summary || 'This action has no parent vision context.'
    };
    
    return NextResponse.json({
      success: true,
      data: enhancedActionDetails
    });
  } catch (error) {
    console.error('Error getting next action:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  }
}