import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { ActionsService } from "../../../../lib/services/actions";
import { actionDataSchema } from "../../../../db/schema";

const deleteActionSchema = z.object({
  child_handling: z.enum(["delete_recursive", "reparent"]).default("reparent"),
  new_parent_id: z.string().uuid().optional(),
});

const updateActionSchema = actionDataSchema.partial().extend({
  done: z.boolean().optional(),
  completion_context: z.object({
    implementation_story: z.string().optional(),
    impact_story: z.string().optional(),
    learning_story: z.string().optional(),
    changelog_visibility: z.string().optional(),
  }).optional(),
}).refine(
  (data) => data.title !== undefined || data.description !== undefined || data.vision !== undefined || data.done !== undefined || data.completion_context !== undefined,
  {
    message: "At least one field (title, description, vision, done, or completion_context) must be provided",
  }
);

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const resolvedParams = await params;
    
    // Get the detailed action data with relationships
    const actionDetails = await ActionsService.getActionDetailResource(resolvedParams.id);
    
    // Parent summaries are now read directly from database columns
    // (they're automatically generated and regenerated by the ParentSummaryService)
    const enhancedActionDetails = {
      ...actionDetails,
      parent_context_summary: actionDetails.parent_context_summary || 'This action has no parent context.',
      parent_vision_summary: actionDetails.parent_vision_summary || 'This action has no parent vision context.'
    };
    
    return NextResponse.json({
      success: true,
      data: enhancedActionDetails
    });
  } catch (error) {
    console.error('Error getting action details:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const body = await request.json();
    const updateParams = updateActionSchema.parse(body);
    const resolvedParams = await params;
    
    const result = await ActionsService.updateAction({
      action_id: resolvedParams.id,
      ...updateParams
    });
    
    return NextResponse.json({
      success: true,
      data: result
    });
  } catch (error) {
    console.error('Error updating action:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 400 }
    );
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const body = await request.json().catch(() => ({}));
    const deleteParams = deleteActionSchema.parse(body);
    const resolvedParams = await params;
    
    const result = await ActionsService.deleteAction({
      action_id: resolvedParams.id,
      ...deleteParams
    });
    
    return NextResponse.json({
      success: true,
      data: result
    });
  } catch (error) {
    console.error('Error deleting action:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 400 }
    );
  }
}